const AMOUNT_UPPER_BOUND = 2 ** 64;
const EXPIRATION_TIMESTAMP_UPPER_BOUND = 2 ** 32;
const NONCE_UPPER_BOUND = 2 ** 32;
const VAULT_ID_UPPER_BOUND = 2 ** 64;
const MINT_TREE_INDEX_SALT = 0x6d696e74;
