# Python library with all the dependencies that should be part of the cairo-lang package.

# src/starkware/cairo/lang/setup.py is run inside the runfiles directory of this target
# to create the cairo-lang package zip.

package(default_visibility = ["//visibility:public"])

exports_files(["cairo_constants.py"])
