package(default_visibility = ["//visibility:public"])

exports_files(["pytest_wrapper.py"])

py_binary(
    name = "gen_python_exe",
    srcs = ["gen_python_exe.py"],
    main = "gen_python_exe.py",
)
